import type {BattleState,Detachment,Enhancement,PackageManifest,Profile,RosterUnit,RulesManifest,Stratagem,UnitDetail,UnitIndex} from './types';
import {canon} from './rules';

const DB='field-companion';
const VERSION=2;
const RULE_STORES=['factions','units','profiles','weapons','abilities','keywords','detachments','enhancements','stratagems','points','leaders','source','coreRules','community40kdc','dependencies','searchIndex'] as const;
type RuleStore=typeof RULE_STORES[number];
const PACKAGE_STORE:Record<string,RuleStore>={units:'units',profiles:'profiles',weapons:'weapons',abilities:'abilities',keywords:'keywords',detachments:'detachments',enhancements:'enhancements',stratagems:'stratagems',points:'points',leaders:'leaders',source:'source','core-rules':'coreRules','community-40kdc':'community40kdc'};

function open(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB,VERSION);request.onupgradeneeded=event=>{const db=request.result;for(const name of ['system',...RULE_STORES,'user','battle','staging'])if(!db.objectStoreNames.contains(name))db.createObjectStore(name,{keyPath:'id'});if(event.oldVersion<1){/* initial durable local tree */}};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
function done(tx:IDBTransaction){return new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error);tx.onerror=()=>reject(tx.error);});}
function request<T>(r:IDBRequest<T>){return new Promise<T>((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
const json=(value:unknown)=>JSON.stringify(value);
async function digest(value:string){const bytes=new TextEncoder().encode(value);const hash=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('');}
function packageUrl(file:string,remote:boolean){return remote?`https://raw.githubusercontent.com/JinkoJink/40k-field-companion/main/public/${file}`:`./${file}`;}
export async function system<T>(id:string,fallback:T):Promise<T>{const db=await open();const tx=db.transaction('system','readonly');const record=await request<any>(tx.objectStore('system').get(id));await done(tx);return record?.value??fallback;}
export async function putSystem(id:string,value:unknown){const db=await open();const tx=db.transaction('system','readwrite');tx.objectStore('system').put({id,value});await done(tx);}
async function getAll<T>(store:string):Promise<T[]>{const db=await open();const tx=db.transaction(store,'readonly');const rows=await request<T[]>(tx.objectStore(store).getAll());await done(tx);return rows;}
function normalizeRecord(packageName:string,row:any,index:number){if(row.id)return row;if(packageName==='points')return{...row,id:`points:${row.unitId}`};if(packageName==='profiles')return{...row,id:`profile:${row.unitId}`};if(packageName==='leaders')return{...row,id:`leader:${row.leaderUnitId}`};if(packageName==='source')return{...row,id:`source:${index}`};return{...row,id:`${packageName}:${index}`};}
export function validatePackagePayload(name:string,payload:any){if(![1,2].includes(payload?.schemaVersion)||payload?.package!==name||!Array.isArray(payload.records))throw new Error(`Invalid ${name} package schema.`);const seen=new Set<string>();for(const[index,raw]of payload.records.entries()){const row=normalizeRecord(name,raw,index);if(!row.id||seen.has(row.id))throw new Error(`Duplicate or missing stable ID in ${name}.`);seen.add(row.id);}}
export function changedPackageNames(local:RulesManifest,remote:RulesManifest){return Object.entries(remote.factions.necrons.packages).filter(([name,info])=>local.factions.necrons.packages[name]?.hash!==info.hash).map(([name])=>name);}
async function fetchPackage(info:PackageManifest,remote:boolean){const response=await fetch(packageUrl(info.file,remote),{cache:remote?'no-store':'force-cache'});if(!response.ok)throw new Error(`Could not download ${info.file}.`);const body=await response.text();if(await digest(body.trimEnd())!==info.hash)throw new Error(`Hash mismatch for ${info.file}.`);const parsed=JSON.parse(body);validatePackagePayload(parsed.package,parsed);return parsed;}
async function validationContext(changed:Record<string,any>){const units=(changed.units?.records||await getAll<any>('units')).map((x:any,i:number)=>normalizeRecord('units',x,i));const unitIds=new Set(units.map((x:any)=>x.id));if(!unitIds.size)throw new Error('Rules update has no units.');const detachments=(changed.detachments?.records||await getAll<any>('detachments')).map((x:any,i:number)=>normalizeRecord('detachments',x,i));const detachmentIds=new Set(detachments.map((x:any)=>x.id));const enhancements=(changed.enhancements?.records||await getAll<any>('enhancements')).map((x:any,i:number)=>normalizeRecord('enhancements',x,i));for(const row of enhancements)if(row.detachmentId&&!detachmentIds.has(row.detachmentId))throw new Error(`Invalid detachment reference: ${row.detachmentId}.`);for(const name of ['profiles','weapons','abilities','points','leaders']){const rows=(changed[name]?.records||await getAll<any>(PACKAGE_STORE[name])).map((x:any,i:number)=>normalizeRecord(name,x,i));for(const row of rows){if(name==='profiles'&&(!row.characteristics||typeof row.characteristics!=='object'||!Object.keys(row.characteristics).length))throw new Error(`Malformed stat profile: ${row.id}.`);if(row.unitId&&!unitIds.has(row.unitId))throw new Error(`Broken ${name} reference: ${row.unitId}.`);if(row.leaderUnitId&&!unitIds.has(row.leaderUnitId))throw new Error(`Broken leader reference: ${row.leaderUnitId}.`);for(const id of row.targetUnitIds||[])if(!unitIds.has(id))throw new Error(`Missing leader target: ${id}.`);}}}
async function install(manifest:RulesManifest,packages:Record<string,any>,mode:'bootstrap'|'update'){await validationContext(packages);const db=await open();const stores=['system','staging','dependencies','searchIndex',...new Set(Object.keys(packages).map(name=>PACKAGE_STORE[name]).filter(Boolean))];const tx=db.transaction(stores,'readwrite');const staging=tx.objectStore('staging');for(const[name,payload]of Object.entries(packages))staging.put({id:`${manifest.datasetVersion}:${name}`,payload});for(const[name,payload]of Object.entries(packages)){const mappedStore=PACKAGE_STORE[name];if(!mappedStore)continue;const store=tx.objectStore(mappedStore);store.clear();payload.records.forEach((row:any,index:number)=>store.put(normalizeRecord(name,row,index)));}const dependencies=tx.objectStore('dependencies'),search=tx.objectStore('searchIndex');if(packages.units||packages.keywords||packages.weapons||packages.abilities){dependencies.clear();search.clear();const allUnits=packages.units?.records||await request<any[]>(tx.objectStore('units').getAll());for(const unit of allUnits){dependencies.put({id:unit.id,package:'units',dependsOn:['profiles','weapons','abilities','points','leaders','keywords']});search.put({id:unit.id,text:json(unit).toLowerCase()});}}tx.objectStore('system').put({id:'installed',value:{datasetVersion:manifest.datasetVersion,schemaVersion:manifest.schemaVersion,packages:manifest.factions.necrons.packages,lastSuccessfulUpdate:new Date().toISOString(),lastKnownGood:manifest.datasetVersion,mode}});for(const name of Object.keys(packages))staging.delete(`${manifest.datasetVersion}:${name}`);await done(tx);}
export async function initializeRules(){const installed=await system<any>('installed',null);if(installed)return installed;const manifest=await fetch('./data/version.json').then(r=>{if(!r.ok)throw new Error('Bundled rules manifest unavailable.');return r.json()}) as RulesManifest;if(manifest.schemaVersion>VERSION)throw new Error('Bundled rules need a newer app database schema.');const packages:Record<string,any>={};for(const[name,info]of Object.entries(manifest.factions.necrons.packages))packages[name]=await fetchPackage(info,false);await install(manifest,packages,'bootstrap');return system<any>('installed',null);}
export async function checkForUpdates(force=false){const installed=await system<any>('installed',null);if(!installed)throw new Error('Initialize local rules first.');if(!force&&!navigator.onLine)return{status:'offline' as const,changed:[] as string[]};const manifest=await fetch('https://raw.githubusercontent.com/JinkoJink/40k-field-companion/main/public/data/version.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('Update manifest unavailable.');return r.json()}) as RulesManifest;if(manifest.schemaVersion>VERSION)throw new Error('This update needs a newer app database schema.');const changed=Object.entries(manifest.factions.necrons.packages).filter(([name,info])=>installed.packages?.[name]?.hash!==info.hash);if(!changed.length)return{status:'current' as const,changed:[] as string[]};const active=await readBattle();if(active?.active){await putSystem('pending-update',{manifest,changed:changed.map(([name])=>name),detectedAt:new Date().toISOString()});return{status:'deferred' as const,changed:changed.map(([name])=>name)};}const packages:Record<string,any>={};for(const[name,info]of changed)packages[name]=await fetchPackage(info,true);await install(manifest,packages,'update');return{status:'updated' as const,changed:changed.map(([name])=>name)};}

const asStrings=(values:any[])=>values.map(value=>String(value)).filter(Boolean);
function readableEffect(effect:any):string{if(!effect)return'';if(typeof effect==='string')return effect;if(Array.isArray(effect))return effect.map(readableEffect).filter(Boolean).join('; ');if(effect.type==='sequence')return readableEffect(effect.steps);if(effect.type==='conditional')return [readableEffect(effect.condition),readableEffect(effect.effect)].filter(Boolean).join(' → ');const bits=[effect.type,effect.target,effect.dice,effect.threshold!==undefined?`on ${effect.threshold}+`:null,effect.modifier?Object.entries(effect.modifier).map(([k,v])=>`${k} ${Array.isArray(v)?v.join('/'):String(v)}`).join(', '):null].filter(Boolean);return bits.join(' · ').replace(/-/g,' ');}
function profileText(profile:any){return Object.values(profile?.characteristics||{}).filter(Boolean).join(' ');}
function pricingFromDc(raw:any){const rows=raw?.points||[];if(!rows.length)return null;return[{range:'[1,)',costs:rows.map((row:any)=>({models:Number(row.models||1),points:Number(row.cost||0)}))}];}
function dcStats(raw:any){const p=raw?.profiles?.[0]||{},out:Record<string,string>={};for(const key of ['M','T','W','Sv','Ld','OC'])if(p[key]!==undefined&&p[key]!==null)out[key]=String(p[key]);if(p.invuln_sv)out.InSv=String(p.invuln_sv);return out;}
function mergeAbility(profile:any,dcUnit:any,dc:any):Profile{const structured=(dc.abilities||[]).find((ability:any)=>canon(ability.name)===canon(profile.name)&&(!ability.unit_ids?.length||ability.unit_ids.includes(dcUnit?.id)));const description=profileText(profile)||structured?.community_notes||readableEffect(structured?.effect);return{...profile,description:description||undefined,rule:structured?{source:'40kdc',quality:structured.game_version?.dataslate==='launch'?'structured':'provisional',behavior:structured.behavior,scope:structured.scope,usage:structured.usage,effect:structured.effect,gameVersion:structured.game_version}:profile.rule};}
function dcWeaponProfile(row:any,index:number):Profile{return{id:`dc:weapon:${row.id||index}`,name:row.name||row.id,type:row.type||'Weapon',characteristics:Object.fromEntries(Object.entries(row.profile||row.characteristics||{}).map(([k,v])=>[k,String(v??'')]))};}

export async function loadRules(){
 await initializeRules();
 const [units,profiles,weapons,abilities,points,leaders,detachments,enhancements,stratagems,community]=await Promise.all(['units','profiles','weapons','abilities','points','leaders','detachments','enhancements','stratagems','community40kdc'].map(getAll));
 const communityRecord=(community as any[])[0]||{},dc=communityRecord.data||{};const dcUnitByName=new Map<string,any>((dc.units||[]).map((row:any)=>[canon(row.name),row]));const pointMap=new Map((points as any[]).map(x=>[x.unitId,x])),leaderMap=new Map((leaders as any[]).map(x=>[x.leaderUnitId,x]));const details=new Map<string,UnitDetail>();const index:UnitIndex[]=[];
 for(const raw of units as any[]){const dcUnit=dcUnitByName.get(canon(raw.name));const p:any=pointMap.get(raw.id),statProfile=(profiles as any[]).find(x=>x.unitId===raw.id),leader:any=leaderMap.get(raw.id);const categories=Array.from(new Set([...(raw.categories||[]),...asStrings(dcUnit?.keywords||[]),...asStrings(dcUnit?.faction_keywords||[]).map(value=>`Faction: ${value}`)]));const stats={...dcStats(dcUnit),...(statProfile?.characteristics||{})};const unit:UnitDetail={...raw,categories,stats,pricing:p?.pricing||pricingFromDc(dcUnit)||raw.pricing||null,role:p?.role||raw.role||dcUnit?.role||null,attachTo:leader?.targetNames||raw.attachTo||[],sourceVersion:dcUnit?.game_version,weapons:(weapons as any[]).filter(x=>x.unitId===raw.id),abilities:(abilities as any[]).filter(x=>x.unitId===raw.id).map(profile=>mergeAbility(profile,dcUnit,dc))};details.set(unit.id,unit);const{weapons:_w,abilities:_a,options:_o,rules:_r,...summary}=unit;index.push(summary);}
 const known=new Set(index.map(unit=>canon(unit.name)));for(const raw of dc.units||[]){if(known.has(canon(raw.name))||raw.is_legend)continue;const id=`necrons:unit:${canon(raw.name).replace(/\s+/g,'-')}`,categories=[...asStrings(raw.keywords||[]),...asStrings(raw.faction_keywords||[]).map(value=>`Faction: ${value}`)],dcWeapons=(dc.weapons||[]).filter((weapon:any)=>(raw.weapon_ids||[]).includes(weapon.id)).map(dcWeaponProfile),dcAbilities=(dc.abilities||[]).filter((ability:any)=>(raw.ability_ids||[]).includes(ability.ability_id)).map((ability:any)=>({id:`dc:ability:${ability.ability_id}`,name:ability.name,type:'Abilities',characteristics:{Rule:ability.community_notes||readableEffect(ability.effect)},description:ability.community_notes||readableEffect(ability.effect),rule:{source:'40kdc' as const,quality:ability.game_version?.dataslate==='launch'?'structured' as const:'provisional' as const,behavior:ability.behavior,scope:ability.scope,usage:ability.usage,effect:ability.effect,gameVersion:ability.game_version}}));const unit:UnitDetail={id,name:raw.name,legends:Boolean(raw.is_legend),categories,stats:dcStats(raw),pricing:pricingFromDc(raw),role:raw.role||null,attachTo:[],weaponCount:dcWeapons.length,abilityCount:dcAbilities.length,sourceVersion:raw.game_version,weapons:dcWeapons,abilities:dcAbilities,options:[]};details.set(id,unit);const{weapons:_w,abilities:_a,options:_o,...summary}=unit;index.push(summary);}
 const rawDetachments=detachments as any[];const detachmentIdByDc=new Map<string,string>();for(const d of rawDetachments){const supplement=d.community11e||(dc.detachments||[]).find((row:any)=>canon(row.name)===canon(d.name));if(supplement?.id)detachmentIdByDc.set(supplement.id,d.id);}
 const normalizedEnhancements=(enhancements as any[]).map((row:any)=>{const supplemental=row.community11e||(dc.enhancements||[]).find((candidate:any)=>canon(candidate.name)===canon(row.name));const ability=supplemental?.ability_id&&(dc.abilities||[]).find((candidate:any)=>candidate.ability_id===supplemental.ability_id);const e:Enhancement={...row,points:Number(row.points??row.cost??supplemental?.cost??0),detachmentId:row.detachmentId||detachmentIdByDc.get(supplemental?.detachment_id),description:row.description||profileText(row.ruleProfile)||ability?.community_notes||readableEffect(ability?.effect)||undefined,keywordRestrictions:row.keywordRestrictions||row.requiredKeywords||supplemental?.keyword_restrictions||[],allowedHosts:row.allowedHosts||[],upgrade:Boolean(row.upgrade??row.nonCharacterOnly??supplemental?.upgrade_tag),maxTargets:Number(row.maxTargets??row.limit??supplemental?.max_targets??0)||undefined,abilityId:row.abilityId??supplemental?.ability_id,gameVersion:row.gameVersion||supplemental?.game_version};return e;});
 const dets=rawDetachments.map(d=>{const supplemental=d.community11e||(dc.detachments||[]).find((row:any)=>canon(row.name)===canon(d.name));const ruleAbility=supplemental?.detachment_rule_id&&(dc.abilities||[]).find((ability:any)=>ability.ability_id===supplemental.detachment_rule_id);const ruleText=d.ruleText||(!/codex rules required/i.test(d.summary||'')?d.summary:'')||ruleAbility?.community_notes||readableEffect(ruleAbility?.effect)||'';return{...d,dp:Number(d.dp??supplemental?.detachment_points??0),objective:d.objective||supplemental?.force_dispositions?.[0]||'',tags:d.tags||supplemental?.tags||[],ruleText,summary:ruleText||d.summary,enhancements:normalizedEnhancements.filter(e=>e.detachmentId===d.id),stratagemIds:d.stratagemIds||supplemental?.stratagem_ids||[]};}) as Detachment[];
 const normalizedStratagems=(stratagems as any[]).map((row:any)=>{const supplemental=(dc.stratagems||[]).find((candidate:any)=>candidate.id===row.id||canon(candidate.name)===canon(row.name))||row;const ability=(supplemental.ability_id&&(dc.abilities||[]).find((candidate:any)=>candidate.ability_id===supplemental.ability_id))||(dc.abilities||[]).find((candidate:any)=>canon(candidate.name)===canon(row.name));const detachmentId=row.detachmentId||detachmentIdByDc.get(row.detachment_id||supplemental.detachment_id);const description=row.description||ability?.community_notes||readableEffect(ability?.effect)||undefined;return{...row,id:row.id||supplemental.id,name:row.name||supplemental.name,cp:Number(row.cp??row.cp_cost??supplemental.cp_cost),type:row.type||supplemental.type,phases:row.phases||supplemental.phases||['any'],playerTurn:row.playerTurn||row.player_turn||supplemental.player_turn,timing:row.timing||supplemental.timing,when:row.when,target:row.target,effect:row.effect,description,detachmentId,targetRestrictions:row.targetRestrictions||row.target_restrictions||null,restrictionConfidence:row.restrictionConfidence||((row.targetRestrictions||row.target_restrictions)?'structured':'unknown'),gameVersion:row.gameVersion||supplemental.game_version} as Stratagem;});
 return{index,detailMap:details,detachments:dets,stratagems:normalizedStratagems,version:(await system<any>('installed',null))?.datasetVersion};
}

export async function readUser<T>(id:string,fallback:T):Promise<T>{const db=await open();const tx=db.transaction('user','readonly');const row=await request<any>(tx.objectStore('user').get(id));await done(tx);return row?.value??fallback;}
export async function writeUser(id:string,value:unknown){const db=await open();const tx=db.transaction('user','readwrite');tx.objectStore('user').put({id,value});await done(tx);}
export async function readBattle(){const db=await open();const tx=db.transaction('battle','readonly');const row=await request<any>(tx.objectStore('battle').get('active'));await done(tx);return row?.value as BattleState|null||null;}
export async function writeBattle(value:BattleState|null){const db=await open();const tx=db.transaction('battle','readwrite');if(value)tx.objectStore('battle').put({id:'active',value});else tx.objectStore('battle').delete('active');await done(tx);}
export async function migrateLegacy(){if(await system('legacy-migrated',false))return;for(const[key,id]of [['field-companion-roster-v2','roster'],['field-companion-detachments-v1','detachments']] as const){try{const value=localStorage.getItem(key);if(value)await writeUser(id,JSON.parse(value));}catch{}}try{const value=localStorage.getItem('field-companion-battle-v1');if(value)await writeBattle(JSON.parse(value));}catch{}await putSystem('legacy-migrated',true);}
