import type {AttachmentRole,Detachment,Enhancement,Phase,RetinueCondition,RosterUnit,Stratagem,TargetRestrictions,UnitIndex} from './types';

export const canon=(value:unknown)=>String(value??'').toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z0-9]+/g,' ').trim();
export const slug=(value:unknown)=>canon(value).replace(/\s+/g,'-');
function baseKeywords(unit:UnitIndex){return new Set([unit.name,...unit.categories.map(value=>value.replace(/^Faction:\s*/i,''))].map(canon).filter(Boolean));}
function matchesTerm(unit:UnitIndex,term:string,extras:string[]=[]){const wanted=canon(term);if(!wanted)return true;const values=new Set([...baseKeywords(unit),...extras.map(canon)]);if(values.has(wanted))return true;return[...values].some(value=>value===wanted||value.endsWith(` ${wanted}`)||wanted.endsWith(` ${value}`));}
export function selectedEnhancement(entry:RosterUnit,enhancements:Enhancement[]|undefined){return entry.enhancement?(enhancements||[]).find(candidate=>canon(candidate.name)===canon(entry.enhancement)):undefined;}
export function effectiveKeywords(entry:RosterUnit,unit:UnitIndex,enhancements:Enhancement[]|undefined){const enhancement=selectedEnhancement(entry,enhancements);return Array.from(new Set([...unit.categories.map(value=>value.replace(/^Faction:\s*/i,'')),...(enhancement?.grantKeywords||[])]));}
export function entryHasKeyword(entry:RosterUnit,unit:UnitIndex,enhancements:Enhancement[]|undefined,keyword:string){return matchesTerm(unit,keyword,effectiveKeywords(entry,unit,enhancements));}

export function enhancementEligible(enhancement:Enhancement,unit:UnitIndex){const allowedHosts=enhancement.allowedHosts||[];if(allowedHosts.length&&!allowedHosts.some(host=>canon(host)===canon(unit.name)))return false;if((enhancement.exclusionKeywords||[]).some(term=>matchesTerm(unit,term)))return false;const groups=enhancement.keywordRestrictionGroups||[];if(groups.length&&!groups.some(group=>group.every(term=>canon(term)==='necrons'||matchesTerm(unit,term))))return false;const required=(enhancement.keywordRestrictions||[]).filter(term=>canon(term)!=='dnu');if(!groups.length&&required.length&&!required.every(term=>canon(term)==='necrons'||matchesTerm(unit,term)))return false;const hasDnu=(enhancement.keywordRestrictions||[]).some(term=>canon(term)==='dnu');if(hasDnu&&!allowedHosts.length)return false;if(enhancement.kind==='binding'||(hasDnu&&allowedHosts.length))return true;const character=unit.categories.some(category=>canon(category)==='character'),epic=unit.categories.some(category=>canon(category)==='epic hero');if(enhancement.kind==='upgrade'||enhancement.upgrade)return!character;return character&&!epic;}
export function eligibleEnhancementsForUnit(unit:UnitIndex,enhancements:Enhancement[]|undefined){return(enhancements||[]).filter(enhancement=>enhancementEligible(enhancement,unit));}
export function requiredBindingForUnit(unit:UnitIndex,enhancements:Enhancement[]|undefined){return(enhancements||[]).find(enhancement=>enhancement.kind==='binding'&&enhancement.mandatory&&enhancementEligible(enhancement,unit));}
export function enhancementLimit(enhancement:Enhancement){if(enhancement.maxTargets&&enhancement.maxTargets>0)return enhancement.maxTargets;return enhancement.kind==='upgrade'||enhancement.upgrade?3:1;}
export function enhancementCountContribution(enhancement:Enhancement,occurrence:number){if(enhancement.countsTowardLimit===false||enhancement.kind==='binding')return 0;return(enhancement.kind==='upgrade'||enhancement.upgrade)&&occurrence>1?0:1;}
export function isRulesEnhancement(enhancement:Enhancement|undefined){return Boolean(enhancement&&enhancement.kind!=='binding');}

export function retinueConditionFor(unit:UnitIndex):RetinueCondition|undefined{if(unit.retinueCondition)return unit.retinueCondition;const name=canon(unit.name);if(name==='cryptothralls')return{label:'Cryptek Retinue',requiredAttachedKeywords:['Cryptek','Infantry'],forbiddenCompanionNames:['Canoptek Tomb Crawlers'],maxPerBodyguard:1};if(name==='canoptek tomb crawlers')return{label:'Canoptek Retinue',requiredAttachedKeywords:['Cryptek'],forbiddenCompanionNames:['Cryptothralls'],maxPerBodyguard:1};return undefined;}
export function attachmentRoleFor(unit:UnitIndex):AttachmentRole|undefined{if(retinueConditionFor(unit))return undefined;if(unit.attachmentRole)return unit.attachmentRole;return unit.attachTo?.length?'leader':undefined;}
function bodyguardIdMatches(unit:UnitIndex,targetId:string){const candidates=[unit.externalId,unit.id.split(':').pop(),slug(unit.name)].filter(Boolean).map(slug);return candidates.includes(slug(targetId));}
export function enhancementUnlocksBodyguard(enhancement:Enhancement|undefined,bodyguard:UnitIndex){return Boolean(enhancement?.attachmentBodyguardIds?.some(id=>bodyguardIdMatches(bodyguard,id)));}
export function canAttachToBodyguard(entry:RosterUnit,unit:UnitIndex,bodyguard:UnitIndex,enhancements:Enhancement[]|undefined){const normal=(unit.attachTo||[]).some(name=>canon(name)===canon(bodyguard.name));return normal||enhancementUnlocksBodyguard(selectedEnhancement(entry,enhancements),bodyguard);}
export function usesConditionalAttachment(entry:RosterUnit,unit:UnitIndex,bodyguard:UnitIndex,enhancements:Enhancement[]|undefined){const normal=(unit.attachTo||[]).some(name=>canon(name)===canon(bodyguard.name));return!normal&&enhancementUnlocksBodyguard(selectedEnhancement(entry,enhancements),bodyguard);}

export function unitMatchesRestrictions(unit:UnitIndex,restrictions?:TargetRestrictions|null,extraKeywords:string[]=[]){if(!restrictions)return true;const required=restrictions.requiredKeywords||[],any=restrictions.anyKeywords||[],excluded=restrictions.excludedKeywords||[],names=restrictions.unitNames||[];if(names.length&&!names.some(name=>canon(name)===canon(unit.name)||matchesTerm(unit,name,extraKeywords)))return false;if(required.length&&!required.every(term=>canon(term)==='necrons'||matchesTerm(unit,term,extraKeywords)))return false;if(any.length&&!any.some(term=>matchesTerm(unit,term,extraKeywords)))return false;if(excluded.some(term=>matchesTerm(unit,term,extraKeywords)))return false;return true;}
export function eligibleStratagemTargets(stratagem:Stratagem,roster:RosterUnit[],units:UnitIndex[],enhancements:Enhancement[]=[]){if(!stratagem.targetRestrictions)return[];return roster.flatMap(entry=>{const unit=units.find(candidate=>candidate.id===entry.unitId);if(!unit)return[];return unitMatchesRestrictions(unit,stratagem.targetRestrictions,effectiveKeywords(entry,unit,enhancements))?[{entry,unit}]:[];});}
export function stratagemAvailable(stratagem:Stratagem,phase:Phase,selectedDetachments:Detachment[],roster:RosterUnit[],units:UnitIndex[]){const selectedIds=new Set(selectedDetachments.flatMap(detachment=>[detachment.id||'',canon(detachment.name)]));if(stratagem.detachmentId&&!selectedIds.has(stratagem.detachmentId)&&!selectedIds.has(canon(stratagem.detachmentId)))return false;if(!stratagem.phases.includes('any')&&!stratagem.phases.includes(phase))return false;if(!stratagem.targetRestrictions)return true;const enhancements=selectedDetachments.flatMap(detachment=>detachment.enhancements||[]);return eligibleStratagemTargets(stratagem,roster,units,enhancements).length>0;}

// Universal Rules Updates v1.0, legal for matched play from 22 July 2026.
// Keep these helpers centralized so faction data cannot silently reintroduce pre-update semantics.
export function modifiedStratagemCpCost(baseCp:number,requestedCost:number|undefined,ruleNamesStratagem:boolean){if(requestedCost===undefined)return Math.max(0,baseCp);if(requestedCost===0&&!ruleNamesStratagem)return Math.max(0,baseCp-1);return Math.max(0,requestedCost);}
export function canOverrideStratagemUsageLimit(ruleNamesStratagem:boolean){return ruleNamesStratagem;}
export function normalizeStratagemRangedTargetingGate(inches:number){return inches===12?18:inches;}
export function identicalReplacementStratagemUseLimit(addsIdenticalReplacementUnit:boolean){return addsIdenticalReplacementUnit?1:undefined;}

export function detachmentAppliesToUnit(detachment:Detachment,unit:UnitIndex){const text=canon(`${detachment.ruleText||detachment.summary||''}`);if(!text)return false;const terms=[unit.name,...unit.categories.map(category=>category.replace(/^Faction:\s*/i,''))].map(canon).filter(term=>term&&term!=='necrons');return terms.some(term=>term.length>3&&text.includes(term));}
export function connectionNotesForEntry(entry:RosterUnit,unit:UnitIndex,roster:RosterUnit[],units:UnitIndex[],enhancements:Enhancement[]|undefined){const notes:string[]=[],retinue=retinueConditionFor(unit),role=attachmentRoleFor(unit),enhancement=selectedEnhancement(entry,enhancements),isMurdermind=canon(enhancement?.name)==='murdermind';if(retinue)notes.push(`${retinue.label}: may join a Bodyguard only when it already contains an attached ${retinue.requiredAttachedKeywords.join(' + ')} model${retinue.forbiddenCompanionNames?.length?`; it cannot share that Bodyguard with ${retinue.forbiddenCompanionNames.join(', ')}`:''}.`);else if(role==='support')notes.push('Support: this unit must be attached to a Bodyguard during army construction. One Support can share that Bodyguard with one Leader.');else if(role==='leader')notes.push('Leader: this unit can share its Bodyguard with one Support.');if(isMurdermind)notes.push('Murdermind: this Cryptek can join Lokhust Destroyers, Lokhust Heavy Destroyers, Ophydian Destroyers or Skorpekh Destroyers. Every model in the resulting Attached unit must have the DESTROYER CULT keyword.');else{if(enhancement?.grantKeywords?.length)notes.push(`${enhancement.name}: gains ${enhancement.grantKeywords.join(' + ')}.`);if(enhancement?.attachmentBodyguardIds?.length){const unlocked=units.filter(candidate=>enhancement.attachmentBodyguardIds!.some(id=>bodyguardIdMatches(candidate,id))).map(candidate=>candidate.name);if(unlocked.length)notes.push(`${enhancement.name}: may attach to ${unlocked.join(', ')}.`);}}if(enhancement?.kind==='binding')notes.push(`${enhancement.name} is a mandatory Necrodermal Binding for this host and does not count as an Enhancement choice.`);if(entry.attachedTo){const target=roster.find(candidate=>candidate.instanceId===entry.attachedTo),targetUnit=target&&units.find(candidate=>candidate.id===target.unitId);if(targetUnit)notes.push(`Attached to ${targetUnit.name}.`);}if(unit.transportCapacity?.capacity)notes.push(`Transport capacity: ${unit.transportCapacity.capacity}. See the transport and arrival abilities below for eligible passengers and arrival conditions.`);return notes;}
export function ruleMetaLine(value:unknown){if(!value)return'';if(typeof value!=='string')return'';return value.split('·').map(part=>part.trim()).filter(part=>part&&!/^(?:provisional|passive|range\b|duration\b)/i.test(part)).join(' · ');}